### ISSUE TITLE
PlexampRPC freezes on startup.

### ISSUE THREAD

**Issue by Azuriye** [Dyvinia/PlexampRPC#11]
Unfortunately, I could not get the logs for why this is happening since the app freezes at startup and I cannot hit Ctrl+C or F5 to show the logs. When the app starts up and I hit F5 it says PlexampRPC has crashed and as usual the app is frozen.

This issue is persistent in version 1.4.0 and above. Version 1.3.2 seems stable but not sure what's causing this issue.

Not to confuse you but I also found something strange when I use a proxy software in version 1.4.0 and above for PlexampRPC it starts up the application just fine. Any idea if this could be some sort of networking issue?

**Comment by cdrscore** [comment]
Same issue I've had since 1.4.0 release. 
1.3.2 is perfect.

**Comment by Dyvinia** [comment]
> it says PlexampRPC has crashed 

does it have any text in the crash window

**Comment by Azuriye** [comment]
> does it have any text in the crash window

No it just freezes up and shows the eventual prompt saying PlexampRPC isn't responding...

**Comment by arlenreyb** [comment]
1.3.2 also does this.

**Comment by Zeninari** [comment]
i wanted to say mine also freezes, i had to keep downgrading until version 1.2.2 finally didn't freeze, theres no logs and unlike others mine never crashes just stays frozen :/

**Comment by Dyvinia** [comment]
do you think you could check if this happens on the lates version?

**Comment by cdrscore** [comment]
> do you think you could check if this happens on the latest version?

Everything works perfectly in the latest version!
