### ISSUE TITLE
Wacatac.H!ml Quarantine

### ISSUE THREAD

**Issue by OldestBen** [Dyvinia/PlexampRPC#17]
# Wacatac.H!ml Quarantine

**Description:**  
While using PlexampRPC, my antivirus flagged and quarantined the software as a potential threat. Specifically, it detected **Trojan:Script/Wacatac.H!ml** and classified it as a severe threat. Based on my understanding of the software and its use, I believe this to be a false positive.

The issue was flagged on Windows Defender.

The following files and paths were affected:
- `C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\PlexampRPC.lnk`
- `E:\PlexampRPC.exe`
- **Process**: `pid:18840, ProcessStart:133743235256528521`
- **Startup Path**: `C:\Users\username\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\PlexampRPC.lnk`

The antivirus notes that the program "executes commands from an attacker," but I believe this detection to be inaccurate, as PlexampRPC is intended for legitimate use. I wanted to raise this issue in case others have encountered the same false positive or if adjustments need to be made to the software to prevent antivirus detection in the future.

**Steps to Reproduce:**
1. Download and install PlexampRPC.
2. Run the application.
3. Windows Defender flags the software and quarantines the `PlexampRPC.exe` file as a potential Trojan:Script/Wacatac.H!ml.

**Results**
The application was quarantined, and a severe threat warning was displayed by Windows Defender.

**System Information:**
- **OS:** Microsoft Windows Version 24H2 (OS Build 26100.2033)
- **Antivirus:** Windows Defender

Link to [VirusTotal](https://www.virustotal.com/gui/file/4bbc3dcf17f23eff0f575ebbfbd6577c3062f72b4b508a1b226b57194d692c21/detection)

**Comment by Dyvinia** [comment]
theres nothing i can really do about it unfortunately
