### ISSUE TITLE
PlexampRPC picks up play on android device 

### ISSUE THREAD

**Issue by tamiko-chan** [Dyvinia/PlexampRPC#19]
I have this running on my desktop, the same computer that is acting as a server. Noticed something interesting if discord is left up on PC and goes into idle, then PlexampRPC picks up playing music through plexamp android. Is this expected behavior?

**Comment by nx6** [comment]
Yes, it would be. Discord-rich-presence-plex does the same thing. Remember that you authorized the app to your Plex account and it's reading the playback status for your user profile. Just like when you are listening to plexamp on your phone and you open the dashboard on the server's web interface and it shows your activity on the phone there.

**Comment by tamiko-chan** [comment]
Ahh thanks, yeah I just forgot to look at the logs. For some reason I thought it was acting on the plexamp windows client, but noticed the gets to server. It is a little weird that it'll only pick up your phone it seemed if desktop is idle. Thanks for the response :)
