### ISSUE TITLE
Feature: server address box, or "use local address" box, in settings

### ISSUE THREAD

**Issue by alyssadev** [Dyvinia/PlexampRPC#8]
This app wasn't getting my listening status from Plex until I manually set the server address and token in the configuration directory. The debug log showed "400 Bad Request" with no further information. It might just be a problem with my setup, double nat or something. A checkbox to indicate that the plex server local address is preferred would help a great deal. Thank you for this very slick app.

**Comment by alyssadev** [comment]
Looking into it, the endpoint used by IPlexAccountClient.GetAccountServersAsync is /pms/servers.xml, but this doesn't return the internal port number for localAddresses, only the external port. [This comment](https://github.com/jensenkd/plex-api/issues/60#issuecomment-1129585941) indicates there's another endpoint that can be used, `https://plex.tv/api/v2/resources?includeHttps=1&includeRelay=1&includeIPv6=1&X-Plex-Token=xxxxxxxxx&X-Plex-Client-Identifier=xxxxxxxxxxx`, this shows all available uris for accessing a given server, including which is the local address, these could be iterated over and tested fairly easily. It would involve sidestepping IPlexAccountClient for local addresses, or PRing this additional/changed data source. I'll get the local address working and make a PR here for further discussion.

**Comment by Dyvinia** [comment]
Alrighty
